#!/bin/bash

# job name
#SBATCH --job-name=steak_script

# How much memory do you need **per core**?
#SBATCH --mem-per-cpu=90G

# time to run
#SBATCH --time=0-96:00

# Number of cores you need
#SBATCH --ntasks=3

# output name
#SBATCH --output=/users/k1893288/t_account/brc_scratch/t_scratch/steak.out

module add utilities/use.dev
module add apps/steak/20190912-singularity

input=LP6005878-DNA_A05
inputnix=/users/k1893288/t_account/brc_scratch/t_scratch/hg19.nix
samtools view -h -o $input.sam $input.bam
rm $input.bam
picard SortSam I=$input.sam O=$input.sorted.sam SORT_ORDER=queryname
rm $input.sam
novoindex hg19.nix hg19.fa
steak --input $input.sorted.sam --paired --aligned --TE-reference hervk_LTR5Hs_Dfam_UC.fa
novoalign -d $inputnix -o SAM -o FullNW -f $input.sorted.1.fastq $input.sorted.2.fastq > $input.sorted.detection.sam
samtools view -S -b $input.sorted.detection.sam > $input.sorted.detection.bam
rm $input.detection.sam
bedtools bamtobed -i $input.sorted.detection.bam > $input.sorted.detection.bed

CONFIRM THIS
bedtools merge -c 4 -o count -d 1000 -i $input.sorted.detection.bed | awk '{if ($4 >=5) print($0);}'- > filtered_novel_ints.bed
